name: wowondertimelineflutterapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.9+19

environment:
  sdk: '>=2.19.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  
  fluttertoast: any
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  chewie: ^1.3.4
  permission_handler: ^10.2.0
  image_picker: ^0.8.7
  path:
  story: ^1.0.0+1
  flutter_social_textfield: ^0.1.2
  encrypt: ^5.0.1
  google_fonts: ^4.0.4
  get_storage: ^2.1.1
  flutter_svg: ^2.0.5
  shared_preferences: ^2.1.0
  just_audio: ^0.9.31
  blurry_modal_progress_hud: ^1.1.0
  flutter_spinkit: ^5.1.0
  cached_network_image: ^3.2.3
  circle_nav_bar: ^2.0.1+1
  native_video_player: ^1.2.0+3
  appinio_video_player: ^1.2.0
  pull_to_refresh: ^2.0.0
  shimmer_pro: ^0.0.6
  url_launcher: ^6.1.10
  photo_view: ^0.14.0
  flutter_polls: ^0.1.2
  # auto_size_text: ^3.0.0
  image_cropper: ^4.0.1
  helpers: ^1.2.0
  share_plus: ^6.3.0
 
  # story_maker: ^1.0.4
  flutter_staggered_animations: ^1.1.1
  # video_player: ^2.6.1
  # story_designer: ^2.0.1
  flashy_tab_bar2: ^0.0.5
  vs_story_designer: ^1.5.1
  flutter_portal: ^1.1.3
  quickalert: ^1.0.1
  flutter_otp_text_field: ^1.1.1
  flutter_native_splash: ^2.2.19
  google_sign_in: ^6.1.4
  sign_in_button: ^3.2.0
  provider: ^6.0.5
  flutter_facebook_auth: ^5.0.11
  sign_in_with_apple: ^5.0.0
  onesignal_flutter: ^3.5.0
  comment_tree: ^0.3.0
  socket_io_client: ^2.0.0
  flutter_io_socket: ^0.0.7
  flutter_local_notifications: ^14.1.0
  flutter_background_service: ^3.0.1
  device_info_plus: ^8.2.2
  adaptive_action_sheet: ^2.0.2
  flutter_rating_bar: ^4.0.1
  flutter_html:
  step_progress_indicator: ^1.0.2
  keyboard_actions: ^4.2.0
  iconforest_flat_icons_social: ^1.0.0+1
  ionicons: ^0.2.2
  flutter_parsed_text: ^2.2.1
  animated_text_kit: ^4.2.2
  flutter_keyboard_visibility: ^5.4.1
  video_editor: ^2.4.0
  record: ^4.4.4
  chat_bubbles: ^1.4.1
  flutter_emoji_gif_picker: ^0.1.4
  emoji_picker_flutter: ^1.6.1
  youtube_player_iframe: ^4.0.4
  like_button: ^2.0.5
  flutter_barcode_scanner: ^2.0.0
  pretty_qr_code: ^2.0.3
  webview_flutter: ^4.2.2
  rating_dialog: ^2.0.4
  store_redirect: ^2.0.1
  detectable_text_field: ^2.1.0
  flutter_hashtags: ^0.0.1
  vimeo_video_player: ^0.0.10
  # agora_rtc_engine: ^6.2.0

  flutter_dotenv: ^5.0.2
  # omni_jitsi_meet: ^1.0.14
  google_mobile_ads: ^3.0.0
  uuid: ^3.0.7
  flutter_custom_clippers: ^2.1.0
  # agora_rtm: ^1.1.1
  flutter_aes_ecb_pkcs5: ^0.1.3
  pointycastle: ^3.7.3
  auto_size_text: ^3.0.0
  # circular_menu: ^2.0.1
  expandable_menu: ^0.0.5
  agora_rtc_engine: ^5.3.0
  agora_uikit: ^1.0.4
  flutter_paypal: ^0.2.0
  internet_connection_checker: ^1.0.0+1
  weather: ^3.0.0
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  advstory: ^0.2.1
  google_one_tap_sign_in: ^1.0.3
  firebase_auth: ^4.7.3
  extension_google_sign_in_as_googleapis_auth: ^2.0.10
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.1
  # video_editor: ^3.0.0
  # ffmpeg_kit_flutter: ^5.1.0


  # agora_rtm: ^1.5.1
  # agora_uikit: ^1.3.3

  # animated_bottom_navigation_bar: ^1.2.0
  # circular_reveal_animation: ^2.0.1
  # flutter_webrtc: ^0.9.34
  # flutter_webrtc_wrapper: ^1.0.2
  # snippet_coder_utils: ^1.0.14
  # agora_rtm: ^1.5.5
  # flutter_state_notifier: ^0.7.3
  # spincircle_bottom_bar: ^2.0.0
  # flutter_speed_dial: ^7.0.0
  # custom_jitsi_meet: ^4.0.35


  # custom_floating_action_button: ^0.0.3
  # floating_action_bubble: ^1.1.4
  # open_file: ^3.2.1
  # flutter_file_downloader: ^1.1.0+1
  # pdf: ^3.10.4






dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
flutter_native_splash:
  color: "#ffffff"
  image: assets/logoSplash.png

  color_dark: "#121212"
  image_dark: assets/logoSplash.png


  android_12:
    image: assets/logoSplash.png
    icon_background_color: "#ffffff"
    image_dark: assets/logoSplash.png
    icon_background_color_dark: "#121212"

  web: false

flutter_icons:
  android: true
  remove_alpha_ios: true
  ios: true
  image_path_ios: "assets/icon.png"
  image_path: "assets/icon.png"
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

   # To add assets to your application, add an assets section, like this:
  assets:
    #  - assets/images/
    #  - assets/images/svg/
    - assets/
    - assets/images/
    # Simple Svg Images Path
    - assets/svg/
    - assets/svg/home/
    - assets/svg/home/publisherBox/
    - assets/svg/reactions/
    - assets/svg/postBottomButtons/
    - assets/svg/profile/
    - assets/svg/setting/
    - assets/svg/setting/privacy/
    - assets/svg/reactions/animated/
    - assets/svg/authentication/
    - assets/svg/menu/
    - assets/svg/membership/
    # Colors Svg Images Path
    - assets/color-svg/menu/
    - assets/color-svg/home/
    - assets/color-svg/chat/
    - assets/color-svg/home/pro/
    - assets/color-svg/post/
    - assets/color-svg/post/bottom/
    - assets/animations/
    - assets/images/svg/
    - assets/ImageNew/
    - assets/sounds/
    - .env
  
